server {
    listen       80;
    server_name  localhost;

    # nginx status endpoint
    location /status {
        stub_status;
        allow 127.0.0.1;   # optional security
        deny all;
    }

    # normal website
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /google {
        proxy_pass https://www.google.com/;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
