apiVersion: apps/v1
kind: Deployment
metadata:
  name: ot-light
  namespace: sr-test
  labels:
    app: ot-light

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ot-light

  template:
    metadata:
      labels:
        app: ot-light

    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: ot-light
          image: registry.buildpiper.in/ot-light:${BP_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m        # 🔽 reduced
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

      imagePullSecrets:
        - name: bp-ecr-repo-regcred
